services:
  - type: web
    name: soporte-colegio
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: TECHNICIAN_USERNAME
        sync: false
      - key: TECHNICIAN_PASSWORD
        sync: false
